"use client";

import * as React from "react";
import Link from "next/link";
import { Alert, Button, Card, CardBody, CardHeader, CardTitle, Chip, Input, Label, Textarea } from "@/components/ui";
import { statusLabel } from "@/components/casework/work-item-shell";
import { useClarificationAnswer, useEditorDraft, useFieldUpdate, useReviewDecision, useSaveEditorDraft, useStartCaseworkRun, useWorkflow } from "@/lib/hooks/use-casework";
import type { Clarification, FieldAssertion, WorkflowAggregate } from "@/lib/api/casework-types";
import { BackendError } from "@/lib/api/real";

const intentKey = () => crypto.randomUUID();
const fieldLabels: Record<string, string> = { purpose: "Mục đích", drug: "Thuốc/phơi nhiễm", event_outcome: "Biến cố/kết quả", indication: "Chỉ định", population: "Quần thể", setting: "Bối cảnh", route: "Đường dùng", dose: "Liều", comparator: "So sánh", time_window: "Khoảng thời gian" };

function fieldName(key: string) { return fieldLabels[key] ?? key; }
export function CaseworkError({ error, aggregate }: { error: unknown; aggregate?: WorkflowAggregate }) {
  if (!error) return null;
  if (error instanceof BackendError && error.status === 409) {
    const details = error.details && typeof error.details === "object" ? error.details as Record<string, unknown> : {};
    const changed = Array.isArray(details.changed_fields) ? details.changed_fields.filter((item): item is string => typeof item === "string") : [];
    const expected = typeof details.expected_version === "number" ? details.expected_version : "bản nháp của bạn";
    const current = typeof details.current_version === "number" ? details.current_version : aggregate ? `v${aggregate.work_item.version}` : "bản máy chủ hiện hành";
    return <Alert tone="caution" title="Có phiên bản mới trên máy chủ"><p>So sánh trước khi thao tác lại: bản bạn gửi <strong>{String(expected)}</strong>; bản hiện hành <strong>{String(current)}</strong>.</p>{changed.length ? <p className="mt-1">Đã đổi: {changed.join(", ")}.</p> : <p className="mt-1">Tải lại aggregate để xem dữ liệu hiện hành; nội dung cũ không bị ghi đè tự động.</p>}</Alert>;
  }
  return <Alert tone="contradict" title="Thao tác chưa hoàn tất">{error instanceof Error ? error.message : "Kiểm tra kết nối và tải lại trước khi tạo thao tác mới."}</Alert>;
}

export function IntakePanel({ id }: { id: string }) {
  const { data, error } = useWorkflow(id);
  const fields = useFieldUpdate(id);
  const answers = useClarificationAnswer(id);
  if (!data) return null;
  const item = data.work_item;
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr]"><div className="space-y-4"><Card><CardHeader><CardTitle>Nguyên văn đã lưu</CardTitle><Chip tone="neutral">Input v{item.input_revision}</Chip></CardHeader><CardBody><p className="whitespace-pre-wrap text-[14px] leading-relaxed">{item.raw_text}</p><p className="mt-3 text-[12px] text-muted-foreground">Bản nguyên văn không bị thay bằng chuẩn hoá. Xác nhận bên phải tạo phiên bản có truy vết.</p></CardBody></Card><Clarifications aggregate={data} onAnswer={(clarification, answer_state, text) => answers.mutate({ expectedVersion: item.version, answers: [{ clarification_id: clarification.id, expected_clarification_version: clarification.version, answer_state, text }], idempotencyKey: intentKey() })} pending={answers.isPending} /></div><div className="space-y-4"><Card><CardHeader><div><CardTitle>Thông tin được trích xuất</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">Agent chỉ đề xuất; xác nhận là hành động của con người.</p></div></CardHeader><CardBody className="space-y-3">{data.field_assertions.length ? data.field_assertions.map((assertion) => <FieldCard key={assertion.assertion_id} assertion={assertion} disabled={fields.isPending} onAction={(action, value, reason) => fields.mutate({ expectedVersion: item.version, operations: [{ assertion_id: assertion.assertion_id, expected_assertion_version: assertion.version, action, value, reason }], idempotencyKey: intentKey() })} />) : <p className="text-[13px] text-muted-foreground">Chưa có đề xuất hoặc quá trình trích xuất đang chạy. Yêu cầu vẫn đã được lưu.</p>}</CardBody></Card>{data.readiness.blockers.length ? <Alert tone="caution" title="Điều đang chặn bước sau"><ul className="list-disc pl-4">{data.readiness.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></Alert> : null}<CaseworkError error={error ?? fields.error ?? answers.error} aggregate={data} /></div></div>;
}

function FieldCard({ assertion, disabled, onAction }: { assertion: FieldAssertion; disabled: boolean; onAction: (action: "confirm" | "correct" | "mark_unknown", value?: string, reason?: string) => void }) {
  const [edit, setEdit] = React.useState(assertion.value ?? "");
  const span = assertion.source_spans[0];
  return <section className="rounded-[var(--radius-control)] border border-border p-3"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-[13px]">{fieldName(assertion.field_key)}</p><Chip tone={assertion.status === "confirmed" ? "support" : assertion.status === "unknown" ? "caution" : "ai"}>{assertion.status === "proposed" ? "Đề xuất" : assertion.status === "confirmed" ? "Đã xác nhận" : "Chưa biết"}</Chip></div><p className="mt-1 text-[14px]">{assertion.value || "Không có giá trị"}</p>{span ? <p className="mt-2 rounded bg-caution-soft px-2 py-1 text-[12px] text-caution-fg">Căn cứ: “{span.quote}” · nguồn v{span.source_version}</p> : <p className="mt-2 text-[12px] text-caution-fg">Thiếu căn cứ nguồn — không xác nhận tự động.</p>}{assertion.status === "proposed" ? <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" disabled={disabled || !span} onClick={() => onAction("confirm")}>Xác nhận</Button><details><summary className="cursor-pointer text-[13px] text-muted-foreground">Sửa và xác nhận</summary><div className="mt-2 flex gap-2"><Input aria-label={`Giá trị sửa cho ${fieldName(assertion.field_key)}`} value={edit} onChange={(event) => setEdit(event.target.value)} /><Button size="sm" variant="outline" disabled={disabled || !edit.trim()} onClick={() => onAction("correct", edit.trim())}>Lưu sửa</Button></div></details><Button size="sm" variant="ghost" disabled={disabled} onClick={() => onAction("mark_unknown", undefined, "Chưa có thông tin")}>Đánh dấu chưa biết</Button></div> : null}</section>;
}

function Clarifications({ aggregate, onAnswer, pending }: { aggregate: WorkflowAggregate; onAnswer: (clarification: Clarification, answerState: "answered" | "unknown", text?: string) => void; pending: boolean }) {
  const [values, setValues] = React.useState<Record<string, string>>({});
  const open = aggregate.clarifications.filter((item) => item.status === "open");
  return <Card><CardHeader><div><CardTitle>Câu hỏi làm rõ</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">“Bắt buộc” chỉ chặn bước liên quan; “hữu ích” không chặn phản hồi giới hạn.</p></div></CardHeader><CardBody className="space-y-3">{open.length ? open.map((item) => <fieldset key={item.id} className="rounded-[var(--radius-control)] border border-border p-3"><legend className="sr-only">{item.question}</legend><div className="flex flex-wrap gap-2"><Chip tone={item.classification === "required_for_next_step" ? "caution" : "neutral"}>{item.classification === "required_for_next_step" ? "Bắt buộc cho bước sau" : "Hữu ích để đầy đủ"}</Chip>{item.blocked_step ? <span className="text-[12px] text-muted-foreground">Chặn: {item.blocked_step}</span> : null}</div><p className="mt-2 text-[14px]">{item.question}</p>{item.reason ? <p className="mt-1 text-[12px] text-muted-foreground">{item.reason}</p> : null}<Label className="sr-only" htmlFor={`answer-${item.id}`}>Trả lời</Label><Textarea id={`answer-${item.id}`} className="mt-2 min-h-20" value={values[item.id] ?? ""} onChange={(event) => setValues((old) => ({ ...old, [item.id]: event.target.value }))} placeholder="Nhập câu trả lời hoặc chọn “Chưa biết”" /><div className="mt-2 flex gap-2"><Button size="sm" disabled={pending || !(values[item.id] ?? "").trim()} onClick={() => onAnswer(item, "answered", values[item.id].trim())}>Lưu trả lời</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => onAnswer(item, "unknown")}>Tôi chưa biết</Button></div></fieldset>) : <p className="text-[13px] text-muted-foreground">Không có câu hỏi đang mở. Câu đã trả lời sẽ không được tạo lại khi tải trang.</p>}</CardBody></Card>;
}

export function EvidencePanel({ id }: { id: string }) {
  const { data } = useWorkflow(id); const start = useStartCaseworkRun(id);
  if (!data) return null;
  return <div className="space-y-4">{data.readiness.can_retrieve_preliminary ? <Alert tone="ai" title="Có thể tìm sơ bộ">Tìm sơ bộ có thể tiếp tục khi còn câu hỏi làm rõ. Kết quả sẽ ghi rõ giả định và chưa được duyệt.</Alert> : null}<Card><CardHeader><div><CardTitle>Lần chạy và tình trạng nguồn</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">Lỗi nguồn khác với không có kết quả.</p></div>{data.allowed_actions.includes("retrieve_preliminary") ? <Button size="sm" disabled={start.isPending} onClick={() => start.mutate({ expectedVersion: data.work_item.version, purpose: "preliminary", idempotencyKey: intentKey() })}>{start.isPending ? "Đang tạo…" : "Tìm sơ bộ"}</Button> : null}</CardHeader><CardBody className="space-y-3">{data.runs.length ? data.runs.map((run) => <section key={run.id} className="rounded-[var(--radius-control)] border border-border p-3"><div className="flex flex-wrap items-center gap-2"><span className="mono text-[12px]">{run.id}</span><Chip tone="ai">{statusLabel(run.status)}</Chip><Chip tone="neutral">{run.purpose === "preliminary" ? "Sơ bộ" : run.purpose}</Chip></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{(run.source_results ?? []).map((result) => <div key={result.source} className="rounded border border-border p-2 text-[13px]"><strong>{result.source}</strong><p>{result.outcome} · coverage: {result.coverage ?? "chưa nêu"}</p>{result.detail ? <p className="text-muted-foreground">{result.detail}</p> : null}</div>)}</div></section>) : <p className="text-[13px] text-muted-foreground">Chưa có lần chạy. Điều này không có nghĩa nguồn không có kết quả.</p>}</CardBody></Card><CaseworkError error={start.error} aggregate={data} /></div>;
}

export function ResponsePanel({ id }: { id: string }) {
  const { data } = useWorkflow(id); const draft = useEditorDraft(id); const save = useSaveEditorDraft(id);
  const [content, setContent] = React.useState<Record<string, string>>({});
  React.useEffect(() => { if (draft.data) setContent(draft.data.content); }, [draft.data]);
  if (!data) return null;
  const saveNow = () => save.mutate({ base_versions: { work_item: data.work_item.version, input_revision: data.work_item.input_revision }, content, version: draft.data?.version, idempotencyKey: intentKey() });
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><div><CardTitle>Phản hồi theo giai đoạn</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">Tự lưu theo actor trên máy chủ; chỉ hiện “đã lưu” sau phản hồi máy chủ.</p></div><span role="status" className="text-[12px] text-muted-foreground">{save.isPending ? "Đang lưu…" : save.data ? `Đã lưu ${new Date(save.data.saved_at).toLocaleTimeString("vi-VN")}` : "Chưa có bản lưu"}</span></CardHeader><CardBody className="space-y-3">{["summary", "evidence", "limits", "recommendation", "follow_up"].map((section) => <div key={section}><Label htmlFor={section}>{section === "summary" ? "Tóm tắt" : section === "evidence" ? "Bằng chứng" : section === "limits" ? "Giới hạn" : section === "recommendation" ? "Khuyến nghị" : "Theo dõi"}</Label><Textarea id={section} className="mt-1 min-h-24" value={content[section] ?? ""} onChange={(event) => setContent((old) => ({ ...old, [section]: event.target.value }))} onBlur={saveNow} /></div>)}<Button onClick={saveNow} disabled={save.isPending}>Lưu nháp máy chủ</Button></CardBody></Card><div className="space-y-4"><Alert tone="caution" title="Chưa phải phản hồi chính thức">Nháp và kết quả sơ bộ không được dùng như phản hồi đã duyệt.</Alert><Card><CardHeader><CardTitle>Phiên bản hiện hành</CardTitle></CardHeader><CardBody>{data.current_response ? <><Chip tone="neutral">{statusLabel(data.work_item.review_status)}</Chip><p className="mt-2 text-[13px]">Phiên bản {data.current_response.version} · hash {data.current_response.content_hash ?? "chưa có"}</p></> : <p className="text-[13px] text-muted-foreground">Chưa có phiên bản phản hồi. Lưu nháp không tự tạo phản hồi chuyên môn.</p>}</CardBody></Card><CaseworkError error={save.error} aggregate={data} /></div></div>;
}

export function ReviewPanel({ id }: { id: string }) {
  const { data } = useWorkflow(id); const [reason, setReason] = React.useState("");
  const review = useReviewDecision(id, data?.current_response?.response_id ?? "");
  if (!data) return null;
  const canReview = data.allowed_actions.includes("review_response");
  const submit = (action: "approve" | "reject" | "changes_requested") => {
    if (!data.current_response || !data.version_basis?.basis_hash || review.isPending) return;
    review.mutate({ expected_version: data.current_response.version, expected_work_version: data.work_item.version, basis_hash: data.version_basis.basis_hash, action, reason, idempotencyKey: intentKey() });
  };
  return <div className="space-y-4"><Alert tone={canReview ? "ai" : "caution"} title={canReview ? "Có thể xem xét bản này" : "Không thể tự duyệt bản này"}>{canReview ? "Máy chủ sẽ kiểm quyền, tác giả và basis khi nhận quyết định." : "Quyền duyệt và tách biệt người soạn do máy chủ quyết định. Nếu bạn là tác giả, hãy chuyển cho người duyệt khác."}</Alert><Card><CardHeader><CardTitle>Snapshot dùng để duyệt</CardTitle></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Work item v{data.work_item.version} · input v{data.work_item.input_revision}</p><p>Basis hash: <span className="mono">{data.version_basis?.basis_hash ?? "Chưa có basis để duyệt"}</span></p><p>Response: {data.current_response ? `${data.current_response.response_id} v${data.current_response.version}` : "Chưa có phản hồi"}</p>{data.version_basis?.stale_reason ? <Alert tone="caution" title="Cần tải và đối chiếu bản mới">{data.version_basis.stale_reason}</Alert> : null}</CardBody></Card>{canReview && data.current_response && data.version_basis?.basis_hash ? <Card><CardHeader><CardTitle>Quyết định độc lập</CardTitle></CardHeader><CardBody className="space-y-3"><Label htmlFor="review-reason">Lý do quyết định</Label><Textarea id="review-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Nêu nhận xét hoặc yêu cầu sửa…" /><div className="flex flex-wrap gap-2"><Button disabled={review.isPending} onClick={() => submit("approve")}>Duyệt phiên bản này</Button><Button variant="outline" disabled={review.isPending || !reason.trim()} onClick={() => submit("changes_requested")}>Yêu cầu sửa</Button><Button variant="danger" disabled={review.isPending || !reason.trim()} onClick={() => submit("reject")}>Từ chối</Button></div><CaseworkError error={review.error} aggregate={data} /></CardBody></Card> : null}<p className="text-[13px] text-muted-foreground">Quyết định duyệt chỉ được gửi với basis token máy chủ đã cung cấp; giao diện không tự tính hoặc thay thế token này.</p></div>;
}

export function AdrPanel({ id }: { id: string }) { const { data } = useWorkflow(id); if (!data?.adr_intake) return null; const adr = data.adr_intake; return <div className="space-y-4"><Alert tone="ai" title="Phiếu ADR đã được lưu">Thiếu cả bốn nhóm tối thiểu vẫn không làm mất intake. Validity và điều kiện báo cáo là hai kết quả độc lập.</Alert><Card><CardHeader><CardTitle>Bốn nhóm tối thiểu</CardTitle><Chip tone={adr.validity === "complete" ? "support" : "caution"}>{adr.validity === "complete" ? "Đủ bốn nhóm" : adr.validity === "incomplete" ? "Chưa đủ bốn nhóm" : "Chưa xác định"}</Chip></CardHeader><CardBody><ul className="grid gap-2 sm:grid-cols-2">{Object.entries(adr.groups).map(([key, group]) => <li key={key} className="rounded border border-border p-3"><strong>{fieldName(key)}</strong><p className="text-[13px] text-muted-foreground">{group.status === "present" ? "Có dữ kiện" : group.status === "missing" ? "Thiếu dữ kiện" : "Chưa biết"}</p></li>)}</ul></CardBody></Card><Card><CardHeader><CardTitle>Điều kiện báo cáo</CardTitle></CardHeader><CardBody><p className="text-[14px]">{adr.reportability.status === "not_assessed" ? "Chưa đánh giá" : statusLabel(adr.reportability.status)}</p><p className="mt-1 text-[13px] text-muted-foreground">{adr.reportability.reason ?? "Không suy ra điều kiện báo cáo từ tính đầy đủ của bốn nhóm."}</p></CardBody></Card></div>; }

export function AuditPanel({ id }: { id: string }) { const { data } = useWorkflow(id); if (!data) return null; return <Card><CardHeader><CardTitle>Lịch sử phiên bản</CardTitle></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Input revision hiện hành: v{data.work_item.input_revision}</p><p>Trạng thái aggregate: work v{data.work_item.version}</p>{data.input_sources.map((source) => <p key={source.source_id} className="rounded border border-border p-2"><span className="mono">{source.source_id}</span> · {source.kind} v{source.source_version} · {new Date(source.created_at).toLocaleString("vi-VN")}</p>)}</CardBody></Card>; }

export function FollowUpsPanel({ id }: { id: string }) { const { data } = useWorkflow(id); if (!data) return null; return <Card><CardHeader><CardTitle>Theo dõi cần thực hiện</CardTitle></CardHeader><CardBody>{data.clarifications.filter((item) => item.status === "open").length ? <p className="text-[13px]">Có {data.clarifications.filter((item) => item.status === "open").length} câu làm rõ đang mở. Chỉ đóng khi có câu trả lời hoặc resolution thực tế.</p> : <p className="text-[13px] text-muted-foreground">Chưa có follow-up đang mở.</p>}</CardBody></Card>; }

export function WorkOverview({ id }: { id: string }) { const { data } = useWorkflow(id); if (!data) return null; return <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Sẵn sàng cho bước tiếp theo</CardTitle></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Tìm sơ bộ: {data.readiness.can_retrieve_preliminary ? "Có thể" : "Chưa thể"}</p><p>Phân tích theo phạm vi: {data.readiness.can_run_scoped_analysis ? "Có thể" : "Chưa thể"}</p><p>Soạn phản hồi giới hạn: {data.readiness.can_draft_limited ? "Có thể" : "Chưa thể"}</p><p>Gửi duyệt: {data.readiness.can_submit_review ? "Có thể" : "Chưa thể"}</p></CardBody></Card><Card><CardHeader><CardTitle>Phục hồi phiên</CardTitle></CardHeader><CardBody><p className="text-[13px] text-muted-foreground">URL giữ mã hồ sơ và tab. Tải lại sẽ lấy aggregate và nháp đã được máy chủ xác nhận cho đúng actor.</p><Link className="mt-3 inline-block text-[13px] underline" href={`/app/work-items/${encodeURIComponent(id)}/response`}>Mở nháp máy chủ</Link></CardBody></Card>{data.work_item.kind === "adr" ? <div className="md:col-span-2"><AdrPanel id={id} /></div> : null}</div>; }
