"use client";

import * as React from "react";
import Link from "next/link";
import { Alert, Button, Card, CardBody, CardHeader, CardTitle, Chip, Input, Label, Select, Textarea } from "@/components/ui";
import { statusLabel } from "@/components/casework/work-item-shell";
import {
  useAdrIntakePatch, useAdrReportability, useApprovedExport, useClarificationAnswer, useCloseFollowUp, useCreateResponse,
  useCaseworkEvents, useEditorDraft, useFieldUpdate, useReviewDecision, useSaveEditorDraft, useStartCaseworkRun, useSubmitReview, useWorkflow,
} from "@/lib/hooks/use-casework";
import { useIntentKey } from "@/lib/hooks/use-intent-key";
import type { Clarification, FieldAssertion, WorkflowAggregate } from "@/lib/api/casework-types";
import { BackendError } from "@/lib/api/real";

const fieldLabels: Record<string, string> = {
  purpose: "Mục đích", drug: "Thuốc/phơi nhiễm", event_outcome: "Biến cố/kết quả", indication: "Chỉ định", population: "Quần thể", setting: "Bối cảnh", route: "Đường dùng", dose: "Liều", comparator: "So sánh", time_window: "Khoảng thời gian",
  identifiable_patient: "Người bệnh có thể định danh", identifiable_reporter: "Người báo có thể định danh", suspected_product: "Sản phẩm nghi ngờ", suspected_reaction: "Phản ứng nghi ngờ",
};
const sections = ["summary", "evidence", "limits", "recommendation", "follow_up"] as const;
const fieldName = (key: string) => fieldLabels[key] ?? key;
const apiCode = (error: unknown) => error instanceof BackendError ? error.code : undefined;

export function CaseworkError({ error, aggregate, onReload, onKeepMine }: { error: unknown; aggregate?: WorkflowAggregate; onReload?: () => void; onKeepMine?: () => void }) {
  if (!error) return null;
  const code = apiCode(error);
  if (error instanceof BackendError && error.status === 409) {
    const details = error.details && typeof error.details === "object" ? error.details as Record<string, unknown> : {};
    const expected = typeof details.expected_version === "number" ? `v${details.expected_version}` : "bản đang soạn";
    const current = typeof details.current_version === "number" ? `v${details.current_version}` : aggregate ? `v${aggregate.work_item.version}` : "bản máy chủ";
    return <Alert tone="caution" title="Có phiên bản mới trên máy chủ"><p>So sánh: {expected} và {current}. Nội dung bạn vừa nhập vẫn được giữ trong biểu mẫu.</p><div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={onReload}>Tải bản mới</Button>{onKeepMine ? <Button size="sm" variant="ghost" onClick={onKeepMine}>Giữ nội dung tôi đang soạn</Button> : null}</div></Alert>;
  }
  if (code === "self_review_forbidden" || code === "self_review") return <Alert tone="caution" title="Không thể tự duyệt">Bạn là tác giả của bản phản hồi này. Hãy chuyển cho dược sĩ khác có quyền duyệt.</Alert>;
  if (code === "idempotency_conflict") return <Alert tone="caution" title="Khoá thao tác không khớp">Thao tác này đã được gửi với nội dung khác. Giữ nguyên biểu mẫu, thay đổi nội dung hoặc tải lại trước khi gửi lại.</Alert>;
  if (code === "basis_invalid" || code === "invalid_state") return <Alert tone="caution" title="Bản phản hồi không còn hiện hành">Dữ liệu nguồn hoặc phiên bản đã đổi. Tải lại và tạo/gửi lại bản phản hồi khi có basis mới.</Alert>;
  return <Alert tone="contradict" title="Thao tác chưa hoàn tất">{error instanceof Error ? error.message : "Kiểm tra kết nối; nội dung hiện tại chưa bị xóa."}</Alert>;
}

function FieldCard({ assertion, workVersion, disabled }: { assertion: FieldAssertion; workVersion: number; disabled: boolean }) {
  const [edit, setEdit] = React.useState(assertion.value ?? "");
  const span = assertion.source_spans[0];
  return <section className="rounded-[var(--radius-control)] border border-border p-3"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-[13px]">{fieldName(assertion.field_key)}</p><Chip tone={assertion.status === "confirmed" ? "support" : assertion.status === "unknown" ? "caution" : "ai"}>{assertion.status === "proposed" ? "Đề xuất" : assertion.status === "confirmed" ? "Đã xác nhận" : "Chưa biết"}</Chip></div><p className="mt-1 text-[14px]">{assertion.value || "Không có giá trị"}</p>{span ? <p className="mt-2 rounded bg-caution-soft px-2 py-1 text-[12px] text-caution-fg">Căn cứ: “{span.quote}” · nguồn v{span.source_version}</p> : <p className="mt-2 text-[12px] text-caution-fg">Thiếu căn cứ nguồn — không xác nhận tự động.</p>}<p className="sr-only">Phiên bản công việc {workVersion}</p>{assertion.status === "proposed" ? <details className="mt-3"><summary className="cursor-pointer text-[13px] text-muted-foreground">Sửa đề xuất trước khi xác nhận</summary><Input className="mt-2" aria-label={`Giá trị sửa cho ${fieldName(assertion.field_key)}`} value={edit} onChange={(event) => setEdit(event.target.value)} disabled={disabled} /></details> : null}</section>;
}

export function IntakePanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const fields = useFieldUpdate(id); const answers = useClarificationAnswer(id);
  const fieldIntent = useIntentKey(`${id}:${workflow.data?.work_item.version ?? ""}`);
  const answerIntent = useIntentKey(`${id}:${workflow.data?.work_item.version ?? ""}`);
  const data = workflow.data; if (!data) return null; const item = data.work_item;
  const actField = (assertion: FieldAssertion, action: "confirm" | "correct" | "mark_unknown", value?: string) => fields.mutate({ expectedVersion: item.version, operations: [{ assertion_id: assertion.assertion_id, expected_assertion_version: assertion.version, action, value, reason: action === "mark_unknown" ? "Chưa có thông tin" : undefined }], idempotencyKey: fieldIntent.key }, { onSuccess: () => fieldIntent.reset() });
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_1fr]"><div className="space-y-4"><Card><CardHeader><CardTitle>Nguyên văn đã lưu</CardTitle><Chip tone="neutral">Input v{item.input_revision}</Chip></CardHeader><CardBody><p className="whitespace-pre-wrap text-[14px] leading-relaxed">{item.raw_text}</p><p className="mt-3 text-[12px] text-muted-foreground">Bản nguyên văn không bị thay bằng chuẩn hoá.</p></CardBody></Card><Clarifications aggregate={data} pending={answers.isPending} onAnswer={(clarification, state, text) => answers.mutate({ expectedVersion: item.version, answers: [{ clarification_id: clarification.id, expected_clarification_version: clarification.version, answer_state: state, text }], idempotencyKey: answerIntent.key }, { onSuccess: () => answerIntent.reset() })} /></div><div className="space-y-4"><Card><CardHeader><CardTitle>Thông tin được trích xuất</CardTitle></CardHeader><CardBody className="space-y-3">{data.field_assertions.map((assertion) => <div key={assertion.assertion_id}><FieldCard assertion={assertion} workVersion={item.version} disabled={fields.isPending} />{assertion.status === "proposed" ? <div className="mt-2 flex gap-2"><Button size="sm" disabled={fields.isPending || !assertion.source_spans[0]} onClick={() => actField(assertion, "confirm")}>Xác nhận</Button><Button size="sm" variant="ghost" disabled={fields.isPending} onClick={() => actField(assertion, "mark_unknown")}>Chưa biết</Button></div> : null}</div>)}{!data.field_assertions.length ? <p className="text-[13px] text-muted-foreground">Chưa có đề xuất. Yêu cầu vẫn đã được lưu.</p> : null}</CardBody></Card><CaseworkError error={workflow.error ?? fields.error ?? answers.error} aggregate={data} onReload={() => void workflow.refetch()} /></div></div>;
}

function Clarifications({ aggregate, onAnswer, pending }: { aggregate: WorkflowAggregate; onAnswer: (item: Clarification, state: "answered" | "unknown", text?: string) => void; pending: boolean }) {
  const [values, setValues] = React.useState<Record<string, string>>({}); const open = aggregate.clarifications.filter((item) => item.status === "open");
  return <Card><CardHeader><div><CardTitle>Câu hỏi làm rõ</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">“Bắt buộc” chỉ chặn đúng bước liên quan; “hữu ích” không chặn phản hồi giới hạn.</p></div></CardHeader><CardBody className="space-y-3">{open.map((item) => <fieldset key={item.id} className="rounded border border-border p-3"><legend className="sr-only">{item.question}</legend><Chip tone={item.classification === "required_for_next_step" ? "caution" : "neutral"}>{item.classification === "required_for_next_step" ? "Bắt buộc cho bước sau" : "Hữu ích để đầy đủ"}</Chip><p className="mt-2 text-[14px]">{item.question}</p><Textarea className="mt-2 min-h-20" aria-label={`Trả lời: ${item.question}`} value={values[item.id] ?? ""} onChange={(event) => setValues((old) => ({ ...old, [item.id]: event.target.value }))} /><div className="mt-2 flex gap-2"><Button size="sm" disabled={pending || !(values[item.id] ?? "").trim()} onClick={() => onAnswer(item, "answered", values[item.id].trim())}>Lưu trả lời</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => onAnswer(item, "unknown")}>Tôi chưa biết</Button></div></fieldset>)}{!open.length ? <p className="text-[13px] text-muted-foreground">Không có câu hỏi đang mở.</p> : null}</CardBody></Card>;
}

export function EvidencePanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const start = useStartCaseworkRun(id); const data = workflow.data;
  const intent = useIntentKey(`${id}:${data?.work_item.version ?? ""}:preliminary`); if (!data) return null;
  const allowed = data.readiness.can_retrieve_preliminary && data.allowed_actions.includes("retrieve_preliminary");
  return <div className="space-y-4">{allowed ? <Alert tone="ai" title="Có thể tìm sơ bộ">Kết quả sơ bộ được ghi rõ là chưa được duyệt.</Alert> : <Alert tone="caution" title="Chưa thể tìm sơ bộ">Hoàn thiện điều kiện máy chủ yêu cầu trước khi tạo lần chạy.</Alert>}<Card><CardHeader><CardTitle>Lần chạy và tình trạng nguồn</CardTitle>{allowed ? <Button size="sm" disabled={start.isPending} onClick={() => start.mutate({ expectedVersion: data.work_item.version, purpose: "preliminary", idempotencyKey: intent.key }, { onSuccess: () => intent.reset() })}>Tìm sơ bộ</Button> : null}</CardHeader><CardBody className="space-y-3">{data.runs.map((run) => <section key={run.id} className="rounded border border-border p-3"><div className="flex gap-2"><Chip tone="ai">{statusLabel(run.status)}</Chip><Chip tone="neutral">{run.purpose === "preliminary_retrieval" ? "Tìm sơ bộ" : run.purpose}</Chip></div>{(run.source_results ?? []).map((result) => <p key={result.source} className="mt-2 text-[13px]"><strong>{result.source}</strong>: {result.outcome} · phạm vi {result.coverage ?? "chưa nêu"}{result.detail ? ` — ${result.detail}` : ""}</p>)}</section>)}{!data.runs.length ? <p className="text-[13px] text-muted-foreground">Chưa có lần chạy; đây không đồng nghĩa không có kết quả.</p> : null}</CardBody></Card><CaseworkError error={start.error} aggregate={data} onReload={() => void workflow.refetch()} /></div>;
}

export function ResponsePanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const remoteDraft = useEditorDraft(id); const save = useSaveEditorDraft(id); const create = useCreateResponse(id);
  const submit = useSubmitReview(id, workflow.data?.current_response?.response_id ?? ""); const exportResponse = useApprovedExport(id);
  const [content, setContent] = React.useState<Record<string, string>>({}); const [dirty, setDirty] = React.useState(false); const [restored, setRestored] = React.useState(false); const [keepMine, setKeepMine] = React.useState(false);
  React.useEffect(() => { if (remoteDraft.data && !dirty && !keepMine) { setContent(remoteDraft.data.content); setRestored(true); } }, [remoteDraft.data, dirty, keepMine]);
  const data = workflow.data; const saveIntent = useIntentKey(JSON.stringify(content)); const createIntent = useIntentKey(`${id}:${JSON.stringify(content)}:${data?.work_item.version ?? ""}`); const submitIntent = useIntentKey(`${data?.current_response?.response_id ?? ""}:${data?.current_response?.version ?? ""}:${data?.version_basis?.basis_hash ?? ""}`);
  if (!data) return null;
  const blocked = workflow.isRefetchError || Boolean(data.version_basis?.stale_reason);
  const saveNow = () => save.mutate({ base_versions: { work_item: data.work_item.version, input_revision: data.work_item.input_revision }, content, version: remoteDraft.data?.version, idempotencyKey: saveIntent.key }, { onSuccess: () => { setDirty(false); setRestored(true); saveIntent.reset(); } });
  const response = data.current_response;
  const canCreate = data.readiness.can_draft_limited && !dirty && !blocked && Object.values(content).some((text) => text.trim());
  const canSubmit = Boolean(response && data.allowed_actions.includes("submit_review") && data.version_basis?.basis_hash && !blocked);
  const canExport = data.work_item.review_status === "approved" && !blocked;
  return <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><div><CardTitle>Phản hồi theo giai đoạn</CardTitle><p className="mt-1 text-[12px] text-muted-foreground">Nháp lưu riêng theo actor và chỉ khôi phục sau khi máy chủ xác nhận.</p></div><span role="status" className="text-[12px] text-muted-foreground">{save.isPending ? "Đang lưu…" : restored ? "Đã khôi phục/lưu nháp máy chủ" : "Chưa có bản lưu"}</span></CardHeader><CardBody className="space-y-3">{sections.map((section) => <div key={section}><Label htmlFor={section}>{({ summary: "Tóm tắt", evidence: "Bằng chứng", limits: "Giới hạn", recommendation: "Khuyến nghị", follow_up: "Theo dõi" })[section]}</Label><Textarea id={section} className="mt-1 min-h-24" value={content[section] ?? ""} onChange={(event) => { setDirty(true); setRestored(false); setContent((old) => ({ ...old, [section]: event.target.value })); }} onBlur={saveNow} /></div>)}<Button onClick={saveNow} disabled={save.isPending || !dirty}>Lưu nháp máy chủ</Button></CardBody></Card><div className="space-y-4"><Alert tone="caution" title="Nháp không phải phản hồi chính thức">Kết quả sơ bộ và nháp không được dùng như bản đã duyệt.</Alert>{blocked ? <Alert tone="caution" title="Đang dùng dữ liệu cũ">{data.version_basis?.stale_reason ?? "Không thể làm mới dữ liệu. Tải lại trước khi gửi duyệt hoặc xuất."}</Alert> : null}<Card><CardHeader><CardTitle>Phát hành và duyệt</CardTitle></CardHeader><CardBody className="space-y-3"><p className="text-[13px]">{response ? `Phản hồi ${response.response_id} v${response.version}: ${statusLabel(data.work_item.review_status)}` : "Chưa tạo phản hồi chuyên môn."}</p><Button size="sm" disabled={!canCreate || create.isPending} onClick={() => create.mutate({ expected_version: data.work_item.version, expected_input_revision: data.work_item.input_revision, sections: content, idempotencyKey: createIntent.key }, { onSuccess: () => createIntent.reset() })}>Tạo phản hồi từ nháp đã lưu</Button><Button size="sm" variant="outline" disabled={!canSubmit || submit.isPending} onClick={() => response && data.version_basis && submit.mutate({ expected_version: response.version, expected_work_version: data.work_item.version, basis_hash: data.version_basis.basis_hash, idempotencyKey: submitIntent.key }, { onSuccess: () => submitIntent.reset() })}>Gửi chờ duyệt</Button><Button size="sm" variant="outline" disabled={!canExport || exportResponse.isPending} onClick={() => exportResponse.mutate()}>Xuất bản đã duyệt</Button>{exportResponse.data ? <pre className="max-h-40 overflow-auto rounded bg-muted p-2 text-[12px]" aria-label="Bản xuất đã duyệt">{exportResponse.data.sections.map((part) => `${part.title ?? part.key ?? ""}\n${part.text ?? ""}`).join("\n\n")}</pre> : null}</CardBody></Card><CaseworkError error={save.error ?? create.error ?? submit.error ?? exportResponse.error} aggregate={data} onReload={() => { setKeepMine(false); void workflow.refetch(); }} onKeepMine={() => setKeepMine(true)} /></div></div>;
}

export function ReviewPanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const [reason, setReason] = React.useState(""); const data = workflow.data;
  const review = useReviewDecision(id, data?.current_response?.response_id ?? ""); const intent = useIntentKey(`${data?.current_response?.response_id ?? ""}:${data?.version_basis?.basis_hash ?? ""}:${reason}`);
  if (!data) return null; const stale = workflow.isRefetchError || Boolean(data.version_basis?.stale_reason) || Boolean(data.stale_approval_reason);
  const canReview = data.allowed_actions.includes("review_response") && !!data.current_response && !!data.version_basis?.basis_hash && !stale;
  const decide = (action: "approve" | "reject" | "changes_requested") => data.current_response && data.version_basis && review.mutate({ expected_version: data.current_response.version, expected_work_version: data.work_item.version, basis_hash: data.version_basis.basis_hash, action, reason, idempotencyKey: intent.key }, { onSuccess: () => intent.reset() });
  return <div className="space-y-4"><Alert tone={canReview ? "ai" : "caution"} title={canReview ? "Có thể duyệt độc lập" : "Chưa thể duyệt"}>{stale ? "Bản duyệt đã cũ hoặc không thể làm mới aggregate. Tải lại trước khi quyết định." : "Quyền duyệt và tách biệt tác giả do máy chủ kiểm soát."}</Alert>{data.stale_approval_reason || data.version_basis?.stale_reason ? <Alert tone="caution" title="Cần duyệt lại">{data.stale_approval_reason ?? data.version_basis?.stale_reason}</Alert> : null}<Card><CardHeader><CardTitle>Snapshot dùng để duyệt</CardTitle></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Work item v{data.work_item.version} · input v{data.work_item.input_revision}</p><p>Basis: <span className="mono">{data.version_basis?.basis_hash ?? "Chưa có"}</span></p><p>Phản hồi: {data.current_response ? `${data.current_response.response_id} v${data.current_response.version}` : "Chưa có"}</p></CardBody></Card>{canReview ? <Card><CardHeader><CardTitle>Quyết định độc lập</CardTitle></CardHeader><CardBody className="space-y-3"><Label htmlFor="review-reason">Lý do quyết định</Label><Textarea id="review-reason" value={reason} onChange={(event) => setReason(event.target.value)} /><div className="flex flex-wrap gap-2"><Button disabled={review.isPending} onClick={() => decide("approve")}>Duyệt phiên bản này</Button><Button variant="outline" disabled={review.isPending || !reason.trim()} onClick={() => decide("changes_requested")}>Yêu cầu sửa</Button><Button variant="danger" disabled={review.isPending || !reason.trim()} onClick={() => decide("reject")}>Từ chối</Button></div></CardBody></Card> : null}<CaseworkError error={review.error} aggregate={data} onReload={() => void workflow.refetch()} /></div>;
}

export function AdrPanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const adrPatch = useAdrIntakePatch(id);
  const reportability = useAdrReportability(id); const data = workflow.data; const [supplement, setSupplement] = React.useState(""); const [groups, setGroups] = React.useState<Record<string, string>>({}); const [reportStatus, setReportStatus] = React.useState<"" | "needs_information" | "reportable" | "not_reportable">("");
  const intent = useIntentKey(`${id}:${supplement}:${JSON.stringify(groups)}:${data?.work_item.version ?? ""}`);
  if (!data?.adr_intake) return null; const adr = data.adr_intake;
  const saveSupplement = () => adrPatch.mutate({ expected_version: data.work_item.version, patch: { supplement_text: supplement, groups: Object.fromEntries(Object.keys(adr.groups).map((key) => [key, { status: groups[key] ?? adr.groups[key].status }])) }, idempotencyKey: intent.key }, { onSuccess: intent.reset });
  const saveReportability = () => reportStatus && reportability.mutate({ expected_version: data.work_item.version, status: reportStatus, idempotencyKey: intent.key }, { onSuccess: intent.reset });
  const canReport = data.allowed_actions.includes("set_adr_reportability");
  return <div className="space-y-4"><Alert tone="ai" title="Phiếu ADR đã được lưu">Thiếu bốn nhóm tối thiểu vẫn được lưu. Tính hợp lệ và điều kiện báo cáo là hai kết quả tách biệt.</Alert><Card><CardHeader><CardTitle>Bổ sung cùng ca</CardTitle></CardHeader><CardBody className="space-y-3"><Textarea aria-label="Nội dung bổ sung cùng ca" value={supplement} onChange={(event) => setSupplement(event.target.value)} placeholder="Bổ sung thông tin cho ca ADR hiện tại…" />{Object.keys(adr.groups).map((key) => <div key={key}><Label htmlFor={`adr-${key}`}>{fieldName(key)}</Label><Select id={`adr-${key}`} className="mt-1" value={groups[key] ?? adr.groups[key].status} onChange={(event) => setGroups((old) => ({ ...old, [key]: event.target.value }))}><option value="missing">Thiếu</option><option value="unknown">Chưa biết</option><option value="present">Có dữ kiện</option></Select></div>)}<Button type="button" disabled={adrPatch.isPending} onClick={saveSupplement}>Lưu bổ sung cùng ca</Button></CardBody></Card><Card><CardHeader><CardTitle>Điều kiện báo cáo</CardTitle></CardHeader><CardBody className="space-y-2"><p>{adr.reportability.status === "not_assessed" ? "Chưa đánh giá" : statusLabel(adr.reportability.status)}</p><p className="text-[13px] text-muted-foreground">{adr.reportability.reason ?? "Không suy ra điều kiện báo cáo chỉ từ bốn nhóm tối thiểu."}</p>{canReport ? <><Select aria-label="Quyết định điều kiện báo cáo" value={reportStatus} onChange={(event) => setReportStatus(event.target.value as typeof reportStatus)}><option value="">Chọn quyết định có thẩm quyền…</option><option value="needs_information">Cần thêm thông tin</option><option value="reportable">Có thể báo cáo</option><option value="not_reportable">Không báo cáo</option></Select><Button size="sm" disabled={reportability.isPending || !reportStatus} onClick={saveReportability}>Lưu đánh giá được uỷ quyền</Button></> : <p className="text-[12px] text-muted-foreground">Chỉ người được uỷ quyền mới có thể đánh giá điều kiện báo cáo.</p>}</CardBody></Card><CaseworkError error={adrPatch.error ?? reportability.error} aggregate={data} onReload={() => void workflow.refetch()} /></div>;
}

export function FollowUpsPanel({ id }: { id: string }) {
  const workflow = useWorkflow(id); const close = useCloseFollowUp(id); const [resolution, setResolution] = React.useState(""); const data = workflow.data; const intent = useIntentKey(`${id}:${resolution}:${data?.work_item.version ?? ""}`);
  if (!data) return null; const items = data.follow_ups ?? [];
  return <Card><CardHeader><CardTitle>Theo dõi cần thực hiện</CardTitle></CardHeader><CardBody className="space-y-3">{items.map((item) => <section key={item.follow_up_id} className="rounded border border-border p-3"><p className="font-medium">{item.note}</p><p className="text-[12px] text-muted-foreground">{statusLabel(item.status)}</p>{["open", "in_progress"].includes(item.status) ? <><Textarea className="mt-2" aria-label={`Resolution ${item.follow_up_id}`} value={resolution} onChange={(event) => setResolution(event.target.value)} /><Button className="mt-2" size="sm" disabled={close.isPending || !resolution.trim()} onClick={() => close.mutate({ followUpId: item.follow_up_id, expected_version: data.work_item.version, status: "done", resolution, idempotencyKey: intent.key }, { onSuccess: () => { setResolution(""); intent.reset(); } })}>Đóng theo dõi</Button></> : null}</section>)}{!items.length ? <p className="text-[13px] text-muted-foreground">Chưa có follow-up đang mở.</p> : null}<CaseworkError error={close.error} aggregate={data} onReload={() => void workflow.refetch()} /></CardBody></Card>;
}

export function AuditPanel({ id }: { id: string }) { const { data } = useWorkflow(id); const events = useCaseworkEvents(id); if (!data) return null; return <Card><CardHeader><CardTitle>Lịch sử phiên bản và thao tác</CardTitle><Button size="sm" variant="ghost" disabled={events.isFetching} onClick={() => void events.refetch()}>Làm mới nhật ký</Button></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Input revision hiện hành: v{data.work_item.input_revision}</p>{data.input_sources.map((source) => <p key={source.source_id} className="rounded border border-border p-2"><span className="mono">{source.source_id}</span> · {source.kind} v{source.source_version} · {new Date(source.created_at).toLocaleString("vi-VN")}</p>)}{events.data?.events.map((event) => <p key={event.id} className="rounded border border-border p-2"><span className="mono">{event.operation_id ?? event.kind}</span> · {statusLabel(event.state ?? "queued")}</p>)}<CaseworkError error={events.error} aggregate={data} onReload={() => void events.refetch()} /></CardBody></Card>; }

export function WorkOverview({ id }: { id: string }) { const { data } = useWorkflow(id); if (!data) return null; return <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Sẵn sàng cho bước tiếp theo</CardTitle></CardHeader><CardBody className="space-y-2 text-[13px]"><p>Tìm sơ bộ: {data.readiness.can_retrieve_preliminary ? "Có thể" : "Chưa thể"}</p><p>Phân tích theo phạm vi: {data.readiness.can_run_scoped_analysis ? "Có thể" : "Chưa thể"}</p><p>Soạn phản hồi giới hạn: {data.readiness.can_draft_limited ? "Có thể" : "Chưa thể"}</p><p>Gửi duyệt: {data.readiness.can_submit_review ? "Có thể" : "Chưa thể"}</p></CardBody></Card><Card><CardHeader><CardTitle>Phục hồi phiên</CardTitle></CardHeader><CardBody><p className="text-[13px] text-muted-foreground">URL giữ mã hồ sơ và tab. Tải lại sẽ lấy aggregate và nháp máy chủ theo đúng actor.</p><Link className="mt-3 inline-block text-[13px] underline" href={`/app/work-items/${encodeURIComponent(id)}/response`}>Mở nháp máy chủ</Link></CardBody></Card></div>; }
